export const kitchenData = [
{
  name: 'Афродита',
  size: '2,4 м.п.',
  topFasad: 'Акрил Neimann',
  bottomFasad: 'Акрил Neimann',
  price: '990 руб',
},
{
  name: 'Акесо',
  size: '2,6 м.п.',
  topFasad: 'Пластик EvoGloss',
  bottomFasad: 'Пластик EvoGloss',
  price: '990 руб',
},
{
  name: 'Эрида',
  size: '4,6 м.п.',
  topFasad: 'Пластик EvoGloss',
  bottomFasad: 'Egger Cерый камень',
  price: '1790 руб',
},
{
  name: 'Антея',
  size: '4,1 м.п.',
  topFasad: 'Egger Дуб орлеанский',
  bottomFasad: 'Egger Дуб орлеанский',
  price: '1290 руб',
},
{
  name: 'Алсеида',
  size: '4,6 м.п.',
  topFasad: 'Акрил Neimann',
  bottomFasad: 'Акрил Neimann',
  price: '2299 руб',
},
{
  name: 'Элпида',
  size: '4,1 м.п.',
  topFasad: 'Egger Фисташка',
  bottomFasad: 'Egger Ясень касино',
  price: '1390 руб',
},
{
  name: 'Галия',
  size: '3,0 м.п.',
  topFasad: 'Egger Лиственница монтана',
  bottomFasad: 'Egger Лиственница монтана',
  price: '1090 руб',
},
{
  name: 'Эрифея',
  size: '3,2 м.п.',
  topFasad: 'Egger Котон',
  bottomFasad: 'Egger Антрацит',
  price: '990 руб',
},
{
  name: 'Фиона',
  size: '4,6 м.п.',
  topFasad: 'Пластик EvoGloss',
  bottomFasad: 'Пластик EvoGloss',
  price: '1590 руб',
},
{
  name: 'Дия',
  size: '3,3 м.п.',
  topFasad: 'Z-фассад + Egger',
  bottomFasad: 'Egger Серый камень',
  price: '1250 руб',
},
{
  name: 'Дриада',
  size: '7,8 м.п.',
  topFasad: 'Акрил Neimann',
  bottomFasad: 'Акрил Neimann',
  price: '3450 руб',
},
{
  name: 'Ирида',
  size: '3,0 м.п.',
  topFasad: 'Акрил ISIC износостойкий',
  bottomFasad: 'Акрил ISIC износостойкий',
  price: '1090 руб',
},
{
  name: 'Каллона',
  size: '3,5 м.п.',
  topFasad: 'Egger Дуб песочный',
  bottomFasad: 'Egger Дуб табак',
  price: '1090 руб',
},
{
  name: 'Мелиноя',
  size: '3,5 м.п.',
  topFasad: 'Z-фассад + Пластик EvoGloss',
  bottomFasad: 'Пластик EvoGloss',
  price: '1190 руб',
},
{
  name: 'Морея',
  size: '4,8 м.п.',
  topFasad: 'Пластик EvoGloss',
  bottomFasad: 'Пластик EvoGloss',
  price: '1990 руб',
},
{
  name: 'Наяда',
  size: '2,5 м.п.',
  topFasad: 'Egger Вудлайн крем',
  bottomFasad: 'Egger Вудлайн мокко',
  price: '790 руб',
},
{
  name: 'Неса',
  size: '4,2 м.п.',
  topFasad: 'Egger Оранжевый',
  bottomFasad: 'Egger Олива кардоба',
  price: '850 руб',
},
{
  name: 'Орфана',
  size: '2,9 м.п.',
  topFasad: 'Пластик EvoGloss',
  bottomFasad: 'Пластик EvoGloss',
  price: '1190 руб',
},
{
  name: 'Селена',
  size: '2,8 м.п.',
  topFasad: 'Пластик EvoGloss',
  bottomFasad: 'Egger Тортона лава',
  price: '1290 руб',
},
{
  name: 'Тиэлла',
  size: '3,2 м.п.',
  topFasad: 'Пластик EvoGloss',
  bottomFasad: 'Пластик EvoGloss',
  price: '1190 руб',
},


];
